apiVersion: gpte.opentlc.com/v1alpha1
kind: Nexus
metadata:
  name: nexus3
spec:
  nexusVolumeSize: 10Gi
  nexusSsl: True
  nexusImageTag: latest
  nexusCpuRequest: 1
  nexusCpuLimit: 2
  nexusMemoryRequest: 2Gi
  nexusMemoryLimit: 2Gi
  nexus_repos_maven_proxy:
  - name: maven-central
    remote_url: https://repo1.maven.org/maven2/
    layout_policy: permissive
  - name: redhat-ga
    remote_url: https://maven.repository.redhat.com/ga/
    layout_policy: permissive
  - name: jboss
    remote_url: https://repository.jboss.org/nexus/content/groups/public
  nexus_repos_maven_hosted:
  - name: releases
    version_policy: release
    write_policy: allow_once
  nexus_repos_maven_group:
  - name: maven-all-public
    member_repos:
      - maven-central
      - redhat-ga
      - jboss
  nexus_repos_docker_hosted:
  - name: docker
    http_port: 5000
    v1_enabled: True
  nexus_repos_npm_proxy:
  - name: npm
    remote_url: https://registry.npmjs.org
  nexus_repos_npm_group:
  - name: npm-all
    member_repos:
      - npm
